version: '2'
services:
    web:
        build: .
        ports:
            - "6000:6000"
        volumes:
            - .:/code
    #     depends_on:
    #         - redis
    # redis:
    #     image: redis